### ISSUE TITLE
Erro to install

### ISSUE THREAD

**Issue by toshibochan** [sfeakes/homebridge-sprinklerd#2]
I have error to install this homebridge.
sudo npm install -g https://github.com/sfeakes/homebridge-sprinklerd.git

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'https://github.com/sfeakes/homebridge-sprinklerd.git' ]
2 info using npm@6.4.1
3 info using node@v10.14.0
4 verbose npm-session 5fcbd560bf60af4e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/sfeakes/homebridge-sprinklerd.git Command failed: /usr/bin/git submodule update -q --init --recursive
7 silly fetchPackageMetaData fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-8b6a18ea': Permission denied
8 timing stage:rollbackFailedOptional Completed in 3ms
9 timing stage:runTopLevelLifecycles Completed in 3379ms
10 verbose stack Error: Command failed: /usr/bin/git submodule update -q --init --recursive
10 verbose stack fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-8b6a18ea': Permission denied
10 verbose stack
10 verbose stack     at ChildProcess.exithandler (child_process.js:289:12)
10 verbose stack     at ChildProcess.emit (events.js:182:13)
10 verbose stack     at maybeClose (internal/child_process.js:962:16)
10 verbose stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
10 verbose stack     at Socket.emit (events.js:182:13)
10 verbose stack     at Pipe._handle.close (net.js:606:12)
11 verbose cwd /home/pi
12 verbose Linux 4.14.79-v7+
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "https://github.com/sfeakes/homebridge-sprinklerd.git"
14 verbose node v10.14.0
15 verbose npm  v6.4.1
16 error code 128
17 error Command failed: /usr/bin/git submodule update -q --init --recursive
17 error fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-8b6a18ea': Permission denied
18 verbose exit [ 1, true ]

**Comment by toshibochan** [comment]
How to change root passwords?

**Comment by sfeakes** [comment]
That depends on a ton of things.  On a new install you can usually run ‘sudo password root’
